// Document Service
// Authoritative hashing is strictly performed server-side per architectural rules.

import apiClient, { isMockMode } from '../api/client';
import mockStore from '../api/mock/store';

export const documentService = {
  async uploadDocument(file, type) {
    if (isMockMode()) {
      // In mock mode, simulate server-side hashing and storage response
      const fakeServerHash = `0x${Array.from({ length: 64 }, () =>
        Math.floor(Math.random() * 16).toString(16)
      ).join('')}`;
      return {
        docId: `doc-${Date.now()}`,
        type,
        fileName: file.name,
        fileSize: file.size,
        hash: fakeServerHash,
        integrity: 'MATCH',
      };
    }
    // TODO(api-contract): path not yet defined in docs
    const formData = new FormData();
    formData.append('file', file);
    formData.append('type', type);
    return await apiClient.post('/documents/upload', formData, {
      headers: { 'Content-Type': undefined },
    });
  },

  async verifyIntegrity(docId, applicationId) {
    if (isMockMode()) {
      return await mockStore.verifyDocumentIntegrity(docId, applicationId);
    }
    // TODO(api-contract): path not yet defined in docs
    return await apiClient.get(
      `/documents/${encodeURIComponent(docId)}/integrity?applicationId=${encodeURIComponent(applicationId)}`
    );
  },

  async downloadERegistry(applicationId) {
    if (isMockMode()) {
      // Per instructions: "in mock mode show a notice 'E-Registry PDF is generated by the backend and is not available in prototype mode' and do NOT fabricate a file"
      return {
        isMockNotice: true,
        message: 'E-Registry PDF is generated by the backend and is not available in prototype mode.',
      };
    }
    // TODO(api-contract): path not yet defined in docs
    return await apiClient.get(`/applications/${encodeURIComponent(applicationId)}/e-registry/download`);
  },
};

export default documentService;
